version: '3.8'

services:
  etcd1:
    image: quay.io/coreos/etcd:v3.5.9
    environment:
      ETCD_NAME: etcd1
      ETCD_DATA_DIR: /etcd-data
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd1:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd1:2380
      ETCD_INITIAL_CLUSTER: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: pgdba-etcd-cluster
    volumes:
      - etcd1-data:/etcd-data
    networks: [pgdba-net]

  etcd2:
    image: quay.io/coreos/etcd:v3.5.9
    environment:
      ETCD_NAME: etcd2
      ETCD_DATA_DIR: /etcd-data
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd2:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd2:2380
      ETCD_INITIAL_CLUSTER: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: pgdba-etcd-cluster
    volumes:
      - etcd2-data:/etcd-data
    networks: [pgdba-net]

  etcd3:
    image: quay.io/coreos/etcd:v3.5.9
    environment:
      ETCD_NAME: etcd3
      ETCD_DATA_DIR: /etcd-data
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd3:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd3:2380
      ETCD_INITIAL_CLUSTER: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: pgdba-etcd-cluster
    volumes:
      - etcd3-data:/etcd-data
    networks: [pgdba-net]

  pg-primary:
    image: ghcr.io/zalando/spilo-16:3.3-p3
    hostname: pg-primary
    environment:
      SCOPE: pgdba-cluster
      ETCD3_HOSTS: etcd1:2379,etcd2:2379,etcd3:2379
      PGPASSWORD_SUPERUSER: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD must be set in .env}
      PGPASSWORD_STANDBY: ${REPLICATION_PASSWORD:?REPLICATION_PASSWORD must be set in .env}
      PATRONI_SUPERUSER_USERNAME: postgres
      PATRONI_REPLICATION_USERNAME: replicator
    ports:
      - "127.0.0.1:5432:5432"
      - "127.0.0.1:8008:8008"
    depends_on: [etcd1, etcd2, etcd3]
    networks: [pgdba-net]

  pg-replica-1:
    image: ghcr.io/zalando/spilo-16:3.3-p3
    hostname: pg-replica-1
    environment:
      SCOPE: pgdba-cluster
      ETCD3_HOSTS: etcd1:2379,etcd2:2379,etcd3:2379
      PGPASSWORD_SUPERUSER: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD must be set in .env}
      PGPASSWORD_STANDBY: ${REPLICATION_PASSWORD:?REPLICATION_PASSWORD must be set in .env}
      PATRONI_SUPERUSER_USERNAME: postgres
      PATRONI_REPLICATION_USERNAME: replicator
    ports:
      - "127.0.0.1:5433:5432"
      - "127.0.0.1:8009:8008"
    depends_on: [pg-primary]
    networks: [pgdba-net]

  pg-replica-2:
    image: ghcr.io/zalando/spilo-16:3.3-p3
    hostname: pg-replica-2
    environment:
      SCOPE: pgdba-cluster
      ETCD3_HOSTS: etcd1:2379,etcd2:2379,etcd3:2379
      PGPASSWORD_SUPERUSER: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD must be set in .env}
      PGPASSWORD_STANDBY: ${REPLICATION_PASSWORD:?REPLICATION_PASSWORD must be set in .env}
      PATRONI_SUPERUSER_USERNAME: postgres
      PATRONI_REPLICATION_USERNAME: replicator
    ports:
      - "127.0.0.1:5434:5432"
      - "127.0.0.1:8010:8008"
    depends_on: [pg-primary]
    networks: [pgdba-net]

  pgbouncer:
    image: edoburu/pgbouncer:v1.25.1-p0
    environment:
      DB_HOST: pg-primary
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD must be set in .env}
      POOL_MODE: transaction
      MAX_CLIENT_CONN: 1000
      DEFAULT_POOL_SIZE: 20
      AUTH_TYPE: scram-sha-256
    ports:
      - "127.0.0.1:6432:6432"
    depends_on: [pg-primary]
    networks: [pgdba-net]

networks:
  pgdba-net:
    driver: bridge

volumes:
  etcd1-data:
  etcd2-data:
  etcd3-data:
